// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace msg_video_trimmer {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// TrimRequest

TrimRequest::TrimRequest(
  int64_t start_time_ms,
  int64_t end_time_ms,
  bool include_audio)
 : start_time_ms_(start_time_ms),
    end_time_ms_(end_time_ms),
    include_audio_(include_audio) {}

int64_t TrimRequest::start_time_ms() const {
  return start_time_ms_;
}

void TrimRequest::set_start_time_ms(int64_t value_arg) {
  start_time_ms_ = value_arg;
}


int64_t TrimRequest::end_time_ms() const {
  return end_time_ms_;
}

void TrimRequest::set_end_time_ms(int64_t value_arg) {
  end_time_ms_ = value_arg;
}


bool TrimRequest::include_audio() const {
  return include_audio_;
}

void TrimRequest::set_include_audio(bool value_arg) {
  include_audio_ = value_arg;
}


EncodableList TrimRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(start_time_ms_));
  list.push_back(EncodableValue(end_time_ms_));
  list.push_back(EncodableValue(include_audio_));
  return list;
}

TrimRequest TrimRequest::FromEncodableList(const EncodableList& list) {
  TrimRequest decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]),
    std::get<bool>(list[2]));
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(TrimRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(TrimRequest)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<TrimRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by VideoTrimmerHostApi.
const flutter::StandardMessageCodec& VideoTrimmerHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `VideoTrimmerHostApi` to handle messages through the `binary_messenger`.
void VideoTrimmerHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  VideoTrimmerHostApi* api) {
  VideoTrimmerHostApi::SetUp(binary_messenger, api, "");
}

void VideoTrimmerHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  VideoTrimmerHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.loadVideo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_path_arg = args.at(0);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->LoadVideo(path_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.trimVideo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const TrimRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->TrimVideo(request_arg, [reply](ErrorOr<std::string>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.clearCache" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ClearCache([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue VideoTrimmerHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue VideoTrimmerHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace msg_video_trimmer
