// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace msg_video_trimmer {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class VideoTrimmerHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Parameters for a single trim operation.
//
// Times are in milliseconds and must satisfy `0 <= startTimeMs < endTimeMs`
// and `endTimeMs <= duration` of the currently loaded video.
//
// Generated class from Pigeon that represents data sent in messages.
class TrimRequest {
 public:
  // Constructs an object setting all fields.
  explicit TrimRequest(
    int64_t start_time_ms,
    int64_t end_time_ms,
    bool include_audio);

  int64_t start_time_ms() const;
  void set_start_time_ms(int64_t value_arg);

  int64_t end_time_ms() const;
  void set_end_time_ms(int64_t value_arg);

  bool include_audio() const;
  void set_include_audio(bool value_arg);


 private:
  static TrimRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class VideoTrimmerHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t start_time_ms_;
  int64_t end_time_ms_;
  bool include_audio_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Host (native) API implemented on iOS, macOS, Android and Windows.
//
// The web platform does not use this API; it implements the same Dart
// platform interface directly using WebCodecs (see `src/web`).
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class VideoTrimmerHostApi {
 public:
  VideoTrimmerHostApi(const VideoTrimmerHostApi&) = delete;
  VideoTrimmerHostApi& operator=(const VideoTrimmerHostApi&) = delete;
  virtual ~VideoTrimmerHostApi() {}
  // Loads the video at [path] so it can be trimmed.
  virtual void LoadVideo(
    const std::string& path,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Trims the currently loaded video and returns the output file path.
  virtual void TrimVideo(
    const TrimRequest& request,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;
  // Deletes every `video_trimmer_*` output produced by this plugin.
  virtual void ClearCache(std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by VideoTrimmerHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `VideoTrimmerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    VideoTrimmerHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    VideoTrimmerHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  VideoTrimmerHostApi() = default;

};
}  // namespace msg_video_trimmer
#endif  // PIGEON_MESSAGES_G_H_
