// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Parameters for a single trim operation.
///
/// Times are in milliseconds and must satisfy `0 <= startTimeMs < endTimeMs`
/// and `endTimeMs <= duration` of the currently loaded video.
class TrimRequest {
  TrimRequest({
    required this.startTimeMs,
    required this.endTimeMs,
    required this.includeAudio,
  });

  int startTimeMs;

  int endTimeMs;

  bool includeAudio;

  Object encode() {
    return <Object?>[
      startTimeMs,
      endTimeMs,
      includeAudio,
    ];
  }

  static TrimRequest decode(Object result) {
    result as List<Object?>;
    return TrimRequest(
      startTimeMs: result[0]! as int,
      endTimeMs: result[1]! as int,
      includeAudio: result[2]! as bool,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TrimRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return TrimRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Host (native) API implemented on iOS, macOS, Android and Windows.
///
/// The web platform does not use this API; it implements the same Dart
/// platform interface directly using WebCodecs (see `src/web`).
class VideoTrimmerHostApi {
  /// Constructor for [VideoTrimmerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VideoTrimmerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Loads the video at [path] so it can be trimmed.
  Future<void> loadVideo(String path) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.loadVideo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[path]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Trims the currently loaded video and returns the output file path.
  Future<String> trimVideo(TrimRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.trimVideo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Deletes every `video_trimmer_*` output produced by this plugin.
  Future<void> clearCache() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.clearCache$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Trim progress (0–100) streamed to Dart while [VideoTrimmerHostApi.trimVideo]
/// runs. Backed by a platform `EventChannel`.
Stream<double> trimProgress( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel trimProgressChannel =
      EventChannel('dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerEvents.trimProgress$instanceName', pigeonMethodCodec);
  return trimProgressChannel.receiveBroadcastStream().map((dynamic event) {
    return event as double;
  });
}
    
