// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.messagenius.msg_video_trimmer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Parameters for a single trim operation.
 *
 * Times are in milliseconds and must satisfy `0 <= startTimeMs < endTimeMs`
 * and `endTimeMs <= duration` of the currently loaded video.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TrimRequest (
  val startTimeMs: Long,
  val endTimeMs: Long,
  val includeAudio: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrimRequest {
      val startTimeMs = pigeonVar_list[0] as Long
      val endTimeMs = pigeonVar_list[1] as Long
      val includeAudio = pigeonVar_list[2] as Boolean
      return TrimRequest(startTimeMs, endTimeMs, includeAudio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startTimeMs,
      endTimeMs,
      includeAudio,
    )
  }
}
private open class messagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrimRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TrimRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val messagesPigeonMethodCodec = StandardMethodCodec(messagesPigeonCodec());


/**
 * Host (native) API implemented on iOS, macOS, Android and Windows.
 *
 * The web platform does not use this API; it implements the same Dart
 * platform interface directly using WebCodecs (see `src/web`).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VideoTrimmerHostApi {
  /** Loads the video at [path] so it can be trimmed. */
  fun loadVideo(path: String, callback: (Result<Unit>) -> Unit)
  /** Trims the currently loaded video and returns the output file path. */
  fun trimVideo(request: TrimRequest, callback: (Result<String>) -> Unit)
  /** Deletes every `video_trimmer_*` output produced by this plugin. */
  fun clearCache(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by VideoTrimmerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      messagesPigeonCodec()
    }
    /** Sets up an instance of `VideoTrimmerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VideoTrimmerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.loadVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.loadVideo(pathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.trimVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as TrimRequest
            api.trimVideo(requestArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.clearCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearCache{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PigeonStreamHandler<T>(
    val wrapper: PigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }
  
  fun endOfStream() { 
    sink.endOfStream()
  }
}
      
/**
 * Trim progress (0–100) streamed to Dart while [VideoTrimmerHostApi.trimVideo]
 * runs. Backed by a platform `EventChannel`.
 */
abstract class TrimProgressStreamHandler : PigeonEventChannelWrapper<Double> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: TrimProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerEvents.trimProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonStreamHandler<Double>(streamHandler)
      EventChannel(messenger, channelName, messagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
