// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Parameters for a single trim operation.
///
/// Times are in milliseconds and must satisfy `0 <= startTimeMs < endTimeMs`
/// and `endTimeMs <= duration` of the currently loaded video.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TrimRequest {
  var startTimeMs: Int64
  var endTimeMs: Int64
  var includeAudio: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrimRequest? {
    let startTimeMs = pigeonVar_list[0] as! Int64
    let endTimeMs = pigeonVar_list[1] as! Int64
    let includeAudio = pigeonVar_list[2] as! Bool

    return TrimRequest(
      startTimeMs: startTimeMs,
      endTimeMs: endTimeMs,
      includeAudio: includeAudio
    )
  }
  func toList() -> [Any?] {
    return [
      startTimeMs,
      endTimeMs,
      includeAudio,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return TrimRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TrimRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Host (native) API implemented on iOS, macOS, Android and Windows.
///
/// The web platform does not use this API; it implements the same Dart
/// platform interface directly using WebCodecs (see `src/web`).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VideoTrimmerHostApi {
  /// Loads the video at [path] so it can be trimmed.
  func loadVideo(path: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Trims the currently loaded video and returns the output file path.
  func trimVideo(request: TrimRequest, completion: @escaping (Result<String, Error>) -> Void)
  /// Deletes every `video_trimmer_*` output produced by this plugin.
  func clearCache(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VideoTrimmerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VideoTrimmerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VideoTrimmerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Loads the video at [path] so it can be trimmed.
    let loadVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.loadVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.loadVideo(path: pathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadVideoChannel.setMessageHandler(nil)
    }
    /// Trims the currently loaded video and returns the output file path.
    let trimVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.trimVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trimVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! TrimRequest
        api.trimVideo(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trimVideoChannel.setMessageHandler(nil)
    }
    /// Deletes every `video_trimmer_*` output produced by this plugin.
    let clearCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerHostApi.clearCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCacheChannel.setMessageHandler { _, reply in
        api.clearCache { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearCacheChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Trim progress (0–100) streamed to Dart while [VideoTrimmerHostApi.trimVideo]
/// runs. Backed by a platform `EventChannel`.
class TrimProgressStreamHandler: PigeonEventChannelWrapper<Double> {
  static func register(with messenger: FlutterBinaryMessenger, 
                      instanceName: String = "",
                      streamHandler: TrimProgressStreamHandler) {
    var channelName = "dev.flutter.pigeon.msg_video_trimmer.VideoTrimmerEvents.trimProgress"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<Double>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
